server:
  port: 8080

spring:
  application:
    name: eventsourcing-cqrs-comamndFactory
  datasource:
    url: jdbc:postgresql://localhost:5432/command
    username: command
    password: command
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

axon:
  serializer:
    general: xstream
  axonserver:
    #servers: localhost:8124
    servers: 192.168.0.158:30712

logging:
  level:
    com:
      cqrs:
        command : debug
      org:
        axonframework : debug